// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_i-j1ExEhkhBx6JrkGo_uxoh4YJjcW8o',
    appId: '1:868989915783:web:7122a8f982d787838a9e22',
    messagingSenderId: '868989915783',
    projectId: 'dataton-btdt-98cf9',
    authDomain: 'dataton-btdt-98cf9.firebaseapp.com',
    storageBucket: 'dataton-btdt-98cf9.appspot.com',
    measurementId: 'G-23SMMZQMWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkkvmgBnGRBo_eICIiXNJ-bCsMVnqNec',
    appId: '1:868989915783:android:c7d13d4b5ddec3128a9e22',
    messagingSenderId: '868989915783',
    projectId: 'dataton-btdt-98cf9',
    storageBucket: 'dataton-btdt-98cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtIwyHZRGtP-c5wvMmSLkvpNQ361V6J14',
    appId: '1:868989915783:ios:bae863e3768af7468a9e22',
    messagingSenderId: '868989915783',
    projectId: 'dataton-btdt-98cf9',
    storageBucket: 'dataton-btdt-98cf9.appspot.com',
    iosClientId: '868989915783-874g2j8406itg8543li4fjq7v1p3or6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtIwyHZRGtP-c5wvMmSLkvpNQ361V6J14',
    appId: '1:868989915783:ios:bae863e3768af7468a9e22',
    messagingSenderId: '868989915783',
    projectId: 'dataton-btdt-98cf9',
    storageBucket: 'dataton-btdt-98cf9.appspot.com',
    iosClientId: '868989915783-874g2j8406itg8543li4fjq7v1p3or6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookting',
  );
}
